### ISSUE TITLE
Multi hosts to update

### ISSUE THREAD

**Issue by jkgtw** [joshuaavalon/docker-cloudflare#1]
Can you support multi hosts update?
something like below:
-e HOST=example.com, sub1.example.com, sub2.example.com

Thanks for your tool, very useful!

**Comment by joshuaavalon** [comment]
If they are on the same host, why don't you create a CNAME record instead?

**Comment by jkgtw** [comment]
Yes, you are right, i forgot CNAME can do same thing, thank you again.

**Comment by ElecProg** [comment]
Sometimes (especially if your ISP tends to change your IP every other day) a CNAME record isn't ideal, not entirely sure why but caching seems to be more aggressive and CNAMEs end up not working for me most of the time.

The container doesn't use that much resources (140 KiB) so running once instance per subdomain isn't a real issue however supporting multiple subdomains would make my setup a lot cleaner.

Thanks for this image it works flawlessly!
