### ISSUE TITLE
Use CloudFlare for DNS only

### ISSUE THREAD

**Issue by vurtomatic** [joshuaavalon/docker-cloudflare#10]
Spent a day trying to figure out how to fix ddclient to work with CloudFlare's new API but your solution is much smaller and more specialized. Thank you for creating it!

I have a question which maybe is easily solved with a variable I'm not aware of. For context, I'm running this as a Docker in unRAID.

It works great and updates CloudFlare with my IP, but every time it does that, it switches the setting to "DNS and HTTP proxy (CDN)" (orange cloud) when I want "DNS only" (grey cloud).

![screenshot 2018-11-30 20 36 30](https://user-images.githubusercontent.com/7212035/49324305-d5674780-f4df-11e8-9913-968650de1a06.png)

Can this be set in the Docker's variables that I've missed?

**Comment by joshuaavalon** [comment]
See [README](https://github.com/joshuaavalon/docker-cloudflare/edit/master/README.md)

> `PROXY`: (OPTIONAL) Whether the record is receiving the performance and security benefits of Cloudflare. `true` to enable; `false` to disable. Default: `true`
