### ISSUE TITLE
IPv6 Support?

### ISSUE THREAD

**Issue by rexx0520** [joshuaavalon/docker-cloudflare#12]
As title, does this support IPv6 AAAA Record? Thanks.

**Comment by rexx0520** [comment]
Both of them returns only my ipv6 address

**Comment by joshuaavalon** [comment]
Can you give the develop branch a try?

You can build it locally by

```
docker build --tag "joshava/cloudflare-ddns:latest"
```

Pass environment variable `RECORD_TYPE` as `AAAA`.

**Comment by rexx0520** [comment]
It gets only my IPv4 Address...

**Comment by rexx0520** [comment]
> Both of them returns only my ipv6 address

Sorry... Saw the typo
Both of them returns only my IPv4 address

**Comment by joshuaavalon** [comment]
If that was the case, I don't think it is possible until there is a service that return IPv6 only

**Comment by rexx0520** [comment]
I've found one.
https://v6.ident.me/
this returns only my ipv6 address

**Comment by rexx0520** [comment]
http://ipv6bot.whatismyipaddress.com/
this returns only my ipv6 address too.

**Comment by joshuaavalon** [comment]
New address it pushed to develop branch please try again

**Comment by rexx0520** [comment]
The IPv6 part is working.
But it can't find my existing record.
with FORCE_CREATE enabled, it adds the record with no errors.

**Comment by rexx0520** [comment]
I have both A and AAAA record on a same subdomain, it shouldn't conflict though.

**Comment by joshuaavalon** [comment]
The jq command should select the first id with type AAAA. I would do some more testing later this week.

**Comment by lachlanhunt** [comment]
Even though IPv6 isn't properly supported by this script, the code appears to make incorrect assumptions about the return value of the IP address services.

`curl -s http://icanhazip.com/` (and also tnx.nl) returns my IPv6 address by default, but then the script looks like it will try to set that value as an A record without validating it.  The script really should explicitly request IPv4 and IPv6 addresses independently. (The akamai service doesn't work at all for me for some reason, except by using their dedicated ipv4/ipv6 addresses below)

From the curl man page:

> -4/--ipv4
    If libcurl is capable of resolving an address to multiple IP versions (which it is if it is IPv6-capable), this option tells libcurl to resolve names to IPv4 addresses only. 
-6/--ipv6
    If libcurl is capable of resolving an address to multiple IP versions (which it is if it is IPv6-capable), this option tells libcurl to resolve names to IPv6 addresses only.

Akamai has explicit domains for requesting IPv4 and IPv6 addresses, but icanhazip and tnx should be requested explicitly with IPv4 or IPv6 mode.

```bash
# Returns IPv4 address
curl -4s http://ipv4.whatismyip.akamai.com
curl -4s https://icanhazip.com/
curl -4s https://tnx.nl/ip

# Returns IPv6 address
curl -6s http://ipv6.whatismyip.akamai.com
curl -6s https://icanhazip.com/
curl -6s https://tnx.nl/ip
```

**Comment by joshuaavalon** [comment]
New `IPV6` environment variable is added. It should now support IPv6. 

Thanks for @lachlanhunt advice.
