### ISSUE TITLE
Error: Invalid request headers

### ISSUE THREAD

**Issue by nordge1** [joshuaavalon/docker-cloudflare#18]
I get the following error with the this yml
I does list the correct IP in the 1st line of the error.
Not sure what I'm doing wrong here but it's prob something stupid :-)
Any help would be appreciated.

Error:
cloudflare-ddns     | 2019-05-22T00:48:19.391414821Z IP: ##.###.##.###
cloudflare-ddns     | 2019-05-22T00:48:19.579357388Z Error: Invalid request headers
cloudflare-ddns exited with code 1

YML:

  cloudflare-ddns:
    container_name: cloudflare-ddns
    image: joshuaavalon/cloudflare-ddns:latest
    restart: unless-stopped
    environment:
      - ZONE=####.net
      - HOST=####.net
      - EMAIL=#######@gmail.com
      - API=12ef73424f57eefc###############
      - TTL=1
      - PROXY=true
    network_mode: bridge

**Comment by joshuaavalon** [comment]
Are you using the correct API key? You need the *Global API Key*.

**Comment by nordge1** [comment]
I was not using the global API.
I changed it and still get 

cloudflare-ddns     | 2019-05-22T19:53:27.051646227Z Current time: 2019-05-22 19:53:27
cloudflare-ddns     | 2019-05-22T19:53:27.157526647Z IP: xx.xxx.xx.xxx
cloudflare-ddns     | 2019-05-22T19:53:27.362188046Z Error: Invalid request headers
cloudflare-ddns exited with code 1

**Comment by nordge1** [comment]
I was not using the Gobal API. That fixed it.
Thanks
