### ISSUE TITLE
Latest version no longer works. With "No existing record. Set FORCE_CREATE to any value to force its creation." message.

### ISSUE THREAD

**Issue by doguitar** [joshuaavalon/docker-cloudflare#19]
Since the latest release, using the start command

``` 
# docker run -d 
--name='cloudflare-ddns' 
--net='bridge' 
-e TZ="America/Los_Angeles" 
-e HOST_OS="Unraid" 
-e 'ZONE'='updo.gg' 
-e 'HOST'='updo.gg' 
-e 'EMAIL'='---------------'
 -e 'API'='----------------------' 
-e 'PROXY'='false' 
'joshava/cloudflare-ddns' 7ec20fd34c68823d6ec3b5a2670afb3c297d1496fa66336bc7283319a71a4b01 
```

The result is

```
Current time: 2019-05-25 19:12:14
IP: 68.8.246.106
Zone updo.gg id : 52302aecf4336a0178661a6d72b94bbc
Error: No existing record. Set FORCE_CREATE to any value to force its creation.
```

**Comment by joshuaavalon** [comment]
This image is supposed to update an existing record. It won't create one for you unless you have set `FORCE_CREATE`.

**Comment by doguitar** [comment]
Record exists:
![image](https://user-images.githubusercontent.com/1200188/58386066-6579db80-7faf-11e9-856a-5d65602c5dcb.png)

I believe the zoneid may be incorrect. The url for the page is `https://dash.cloudflare.com/c5b2c476db18d79d400edb30f0fd623d/updo.gg/dns`, should that be the zone id?

**Comment by michaeldavie** [comment]
I'm having the same issue. Everything was working fine until the latest release, but now the container gets into a restart loop and says `Error: No existing record. Set FORCE_CREATE to any value to force its creation.` I double checked all of the API values and nothing has changed.

**Comment by joshuaavalon** [comment]
@doguitar Not zone ID is not in the URL. You can check the zone ID at the bottom of **Overview**.

**Comment by joshuaavalon** [comment]
It should be fixed with the latest release.
