### ISSUE TITLE
Different methods to set IP

### ISSUE THREAD

**Issue by hongkongkiwi** [joshuaavalon/docker-cloudflare#25]
A couple of requests for next version:
* Set IP from custom URL
* Set IP from an environment variable (this would be appropriate when not using the cron function and calling a single docker run for each use
* Set IP from a file (this can be shared on a volume into the docker and updated periodically by an external script. Then during normal run, this file can be checked)

**Comment by joshuaavalon** [comment]
> Set IP from custom URL

This is possible in V2 if your URL return JSON or plain text through a GET request.

> Set IP from an environment variable

What is the point of this? If you are going to change the IP manually, why don't you just go to Cloudflare and set it?

> Set IP from a file

In V2, configuration file is read very time its run. So it should work out of the box.

**Comment by hongkongkiwi** [comment]
> Set IP from an environment variable

In this case, I would have the CURRENT_IP set as an environment variable from a bash script, this script would be called first, would update the CURRENT_IP env. Then the docker would be called as a docker run --rm and it would then run, do it's thing, update and finish.

So, the docker would run something like docker run --rm -e CURRENT_IP=1.1.1.1 .... then inside the docker it would use the CURRENT_IP without doing an external lookup. This is useful for internal adapters but where I want to publish it on an external DNS server.
