### ISSUE TITLE
Empty error message

### ISSUE THREAD

**Issue by jenssegers** [joshuaavalon/docker-cloudflare#3]
I'm getting an empty error message while starting this image:

```
Current time: 2018-07-16 15:37:31
IP: 178.117.190.126
Zone ...
Updating record ... for host ...
Error: 
```

**Comment by jenssegers** [comment]
When starting the `1.2.0` version I get this:

```
{"success":false,"errors":[{"code":6007,"message":"Malformed JSON in request body"}],"messages":[],"result":null}
```

**Comment by joshuaavalon** [comment]
`Malformed JSON in request body`. It seems that you have wrong conflict?

**Comment by revilo951** [comment]
Excuse my ignorance, but how do I know if I have 1.2.0?

**Comment by joshuaavalon** [comment]
https://hub.docker.com/r/joshuaavalon/cloudflare-ddns/tags/

There are different tag of this docker. When you run a docker, you need to specific a tag. By default it is `latest`.
`joshuaavalon/cloudflare-ddns` = `joshuaavalon/cloudflare-ddns:latest`

Tag 1.2.0: https://github.com/joshuaavalon/docker-cloudflare/tree/1.2.0 . Read the readme and run `joshuaavalon/cloudflare-ddns:1.2.0`

**Comment by revilo951** [comment]
Looks like it was a spelling error in the proxy environment variable (fales vs false).

Sorry to have bothered you.

BTW, what's the time period for the check, and was the WAIT env variable actually removed in 1.3.0?

**Comment by joshuaavalon** [comment]
@revilo951 `WAIT` was used in the script to delay each check. It is now moved to crontab, so the option is removed.

**Comment by revilo951** [comment]
Nice.

Thanks for your help.
