### ISSUE TITLE
Need some help understanding how this works

### ISSUE THREAD

**Issue by ovizii** [joshuaavalon/docker-cloudflare#31]
I see we run this like this:

`docker run -d -v ./config.yaml:/app/config.yaml joshava/cloudflare-ddns`

and then?

Does this set the IP as configured but is there a scheduler or cron job somehow to keep updating the IP for the configured domains as soon as my public IP changes?

**Comment by joshuaavalon** [comment]
Cron job is run inside the container. See

```
docker/root/var/spool/cron/crontabs/root
```

**Comment by gurabli** [comment]
> ```
> docker/root/var/spool/cron/crontabs/root
> ```

The same question I wanted to ask. If I'm correct, a cron is triggered every 3 minutes or so? Could this be changed, if yes, how?
And if it is left default, there is no problem of running it so frequently, like CF hit limit or something?

**Comment by joshuaavalon** [comment]
You can change it by mounting a different cronfile there.
