### ISSUE TITLE
Getting errors since this morning about "Invalid TTLs"

### ISSUE THREAD

**Issue by ovizii** [joshuaavalon/docker-cloudflare#33]
```
2020-01-21T09:08:19.019Z [INFO ]: Cloudflare DDNS end                                          │
│   2020-01-21T09:10:01.009Z [INFO ]: Cloudflare DDNS start                                        │
│   2020-01-21T09:10:03.671Z [INFO ]: Try to update record for  ***redacted***                │
│   Failed to update ***redacted***.                                                          │
│   Failed API request:                                                                            │
│   {                                                                                              │
│     "errors": [                                                                                  │
│       {                                                                                          │
│         "code": 9021,                                                                            │
│         "message": "Invalid TTL. Must be between 120 and 2,147,483,647 seconds, or 1 for autom   │
│   atic"                                                                                          │
│       }                                                                                          │
│     ]                                                                                            │
│   }                                                                                              │
│   2020-01-21T09:10:05.429Z [INFO ]: Cloudflare DDNS end 
```

Any ideas what could be wrong?

**Comment by Nicras** [comment]
for me the same

**Comment by joshuaavalon** [comment]
Which version are you using? I did not get any errors.

**Comment by joshuaavalon** [comment]
My guess is you are still using V1, because V2 does not support TTL as Cloudflare does not allow to change it anymore.

**Comment by Nicras** [comment]
Hey, no it's V2 based on the yaml with multi domain support

**Comment by Nicras** [comment]
it worked absolutely smooth until yesterday night

**Comment by Nicras** [comment]
My container has an environment variable named TTL, which was empty all the time. After the error occured, I tried to set this to 1 for automatic, as stated in your documentation

**Comment by ovizii** [comment]
> 
> 
> My guess is you are still using V1, because V2 does not support TTL as Cloudflare does not allow to change it anymore.

I'm totally lost, can you point me towards some documentation where I can read up on V1 / V2 ? is that something I can decide?

This is the documentation I followed: https://joshuaavalon.github.io/docker-cloudflare/guide/configuration.html

**Comment by ovizii** [comment]
> 
> 
> My container has an environment variable named TTL, which was empty all the time. After the error occured, I tried to set this to 1 for automatic, as stated in your documentation

Can you please share the link to the documentation about TTL? After getting the error I searched here and couldn't find anything about TTL: https://joshuaavalon.github.io/docker-cloudflare/guide/configuration.html#environment-variables

**Comment by Nicras** [comment]
it was the documentation for V1 and was just a test with this TTL thing

https://hub.docker.com/r/joshuaavalon/cloudflare-ddns

**Comment by ovizii** [comment]
yeah, thx. meanwhile I did a docker inspect containername and found the empty ENV variable for TTL. Set it to 1 and no changes.

**Comment by Nicras** [comment]
I resolved the error by stopping the container, deleting the image, downloading the image again with latest tag and starting the container again

**Comment by ovizii** [comment]
I tried:
```
docker-compose down
docker image rm joshava/cloudflare-ddns:latest
docker-compose up -d
```

and the error is gone.

very weird :-(

**Comment by joshuaavalon** [comment]
@ovizii Pulling the latest image update the container to V2.

Here is the [migration note](https://joshuaavalon.github.io/docker-cloudflare/migration.html) about V2.

> I'm totally lost, can you point me towards some documentation where I can read up on V1 / V2 ? is that something I can decide?
[Here](https://api.cloudflare.com/#dns-records-for-a-zone-update-dns-record) is the API documentation. As you can see, `ttl` has change from number to `{}`. This is probably due to changes inside Cloudflare. You also cannot change TTL in the web UI if you enable CDN.

**Comment by ovizii** [comment]
> 
> 
> @ovizii Pulling the latest image update the container to V2.
> 
> Here is the [migration note](https://joshuaavalon.github.io/docker-cloudflare/migration.html) about V2.
> 
> > I'm totally lost, can you point me towards some documentation where I can read up on V1 / V2 ? is that something I can decide?
> 
> [Here](https://api.cloudflare.com/#dns-records-for-a-zone-update-dns-record) is the API documentation. As you can see, `ttl` has change from number to `{}`. This is probably due to changes inside Cloudflare. You also cannot change TTL in the web UI if you enable CDN.

Thanks, I understand. CF had an API upgrade, not you, I thought your container had an upgrade from V1 to V2 and couldn't find anything about it :-)
