### ISSUE TITLE
[Bug] IPv6 fetch fails. 

### ISSUE THREAD

**Issue by buliwyf42** [joshuaavalon/docker-cloudflare#34]
**Describe the bug**
I try to update 2 hosts with a and aaaa records.
While fetching the IPv6 address i only get an IPv4 address.
The error in the log looks like.
```
Fail to fetch ip from https://v6.ident.me/.json. (request to https://v6.ident.me/.json failed, reason: getaddrinfo ENOTFOUND v6.ident.me v6.ident.me:443)
Fail to fetch ip from https://v6.ident.me/.json. (request to https://v6.ident.me/.json failed, reason: getaddrinfo ENOTFOUND v6.ident.me v6.ident.me:443)
Fail to fetch ip from https://api6.ipify.org?format=json. (Not IPv6: 188.xxx.xxx.xxx)
Fail to fetch ip from https://api6.ipify.org?format=json. (Not IPv6: 188.xxx.xxx.xxx)
```

When i change the network mode to "host" it works. 
Probably because the host has an IPv6 address. 
The normal mode is bridge mode on the synology. 

**To Reproduce**
Just deploy the actual version

**Expected behavior**
The fetch should get an response from ipify.org with an IPv6 address

**Output log**
If applicable, add output log to help explain your problem.

**Environment:**

- OS: Synology
- Docker: 18.09.8

**Comment by joshuaavalon** [comment]
There is nothing I can do as I do not provide the IP echo service.

You can change to another IP echo service via [configuration](https://joshuaavalon.github.io/docker-cloudflare/guide/configuration.html). You can point the `ipv6` api to either a text response or json response api.
