### ISSUE TITLE
v4.ident.me JSON error

### ISSUE THREAD

**Issue by Coder84619** [joshuaavalon/docker-cloudflare#37]
I'm trying to use the container, however I'm stuck getting these errors: 

Fail to fetch ip from https://v4.ident.me/.json. (request to https://v4.ident.me/.json failed, reason: unable to get local issuer certificate) | stderr
-- | --

Fail to fetch ip from https://v4.ident.me/.json. (invalid json response body at https://v4.ident.me/.json reason: Unexpected token . in JSON at position 7) | stderr

Any ideas?

**Comment by joshuaavalon** [comment]
It seems like https://v4.ident.me/.json is reposing text format instead of JSON format. I will update the code to try to catch the error.

**Comment by danielb7390** [comment]
I'm getting the same but it seems to be updating anyway? Can't be 100% sure, my ip is dynamic but most of the time it only changes once a year!
```
2020-07-20T06:35:00.226Z [INFO ]: Cloudflare DDNS start
Fail to fetch ip from https://v4.ident.me/.json. (invalid json response body at https://v4.ident.me/.json reason: Unexpected token . in JSON at position 6)
Fail to fetch ip from https://v4.ident.me/.json. (invalid json response body at https://v4.ident.me/.json reason: Unexpected token . in JSON at position 6)
2020-07-20T06:35:02.194Z [INFO ]: Skipped updating record for <redacted>
2020-07-20T06:35:02.194Z [INFO ]: Updated <redacted> with 148.x.x.x
2020-07-20T06:35:02.612Z [INFO ]: Skipped updating record for <redacted>
2020-07-20T06:35:02.612Z [INFO ]: Updated <redacted> with 148.x.x.x
```

**Comment by joshuaavalon** [comment]
@danielb7390 This is because the default configuration used two IP providers. It used another one if the first one is failed. ident.me has already been removed from the default configuration.
