### ISSUE TITLE
[Feature] cron time in configuration

### ISSUE THREAD

**Issue by machond** [joshuaavalon/docker-cloudflare#45]
Could you add cron time in config file to be able to manipulate how often update goes?

**Comment by joshuaavalon** [comment]
I have been think on it but no one seems to need it. Now, someone need it, I will try to write it on this weekend.

**Comment by machond** [comment]
There is a lot ddns tools for cloudflare, but only yours seems to by fully configurable. I like idea for having control on all things and variables.
Great you also like this approach. Waiting for new version to test.

**Comment by joshuaavalon** [comment]
You should now able to configure via environment variable `CRON`. You cannot configure via configuration file because only the script run will read the configuration file.
