### ISSUE TITLE
[Bug] <connect ECONNREFUSED 127.0.0.1:80>

### ISSUE THREAD

**Issue by hinyb** [joshuaavalon/docker-cloudflare#54]
**Describe the bug**
When i want update the IP address of my Cloudflare DNS i got this error.

**To Reproduce**
When i want update the IP address of my Cloudflare DNS i got this error.
My config:
ipv6:
  - type: json
    url: v6.ident.me/.json
    fields:
      - address
  - type: json
    url: api6.ipify.org?format=json
    fields:
      - ip

**Expected behavior**
Run container without this error.

**Output log**
[warn] Fail to fetch ip from v6.ident.me/.json. (connect ECONNREFUSED 127.0.0.1:80)
[warn] Fail to fetch ip from api6.ipify.org?format=json. (connect ECONNREFUSED 127.0.0.1:80)
[error] Failed to update www.hinyb.top. (Cannot fetch any IPs!)
[info] Cloudflare DDNS end

**Environment:**

- OS: Ubuntu
- Docker: 20.10.11
- Version: lastest

**Comment by favonia** [comment]
Out of curiosity, is there a reason to remove `https` from the URLs?

**Comment by joshuaavalon** [comment]
You need `http://` or `https://` in the url.
