### ISSUE TITLE
Do not request update API when ip has not change.

### ISSUE THREAD

**Issue by aaftio** [joshuaavalon/docker-cloudflare#6]
Will it change to do not request the update API unless the ip different with current cloudflare check result ?
I think it can reduce the API request.

**Comment by joshuaavalon** [comment]
https://github.com/joshuaavalon/docker-cloudflare/blob/80c85468e419b6889fc100a405f0a4c1dc8cb6d9/cloudflare.sh#L47-L55

> Will it change to do not request the update API unless the ip different with current cloudflare check result ?
I think it can reduce the API request.

How do you check Cloudflare IP of a domain? Use an API request? Use more API requests to reduce API requests.🤔

Anyway, it has a local cache of the last update IP. If it does not change, it won't update. Please read the code youself. It even has comment on it.

**Comment by aaftio** [comment]
https://github.com/joshuaavalon/docker-cloudflare/blob/80c85468e419b6889fc100a405f0a4c1dc8cb6d9/cloudflare.sh#L87-L91

Sorry, maybe I was a bit oversensitive, because this step can get current IP on cloudflare. But now it is no longer that important, because there is a local cache. Thank you!
