### ISSUE TITLE
Small thing: support local TZ?

### ISSUE THREAD

**Issue by toddcurry** [joshuaavalon/docker-cloudflare#9]
Really small thing, but could you allow for a user to pass a timezone (TZ) into Alpine, so that the "Current Time" can reflect local (server) time?  Would help this sysadmin... . Thx
-e TZ="America/Chicago" \

**Comment by joshuaavalon** [comment]
You can fork the project and change 

https://github.com/joshuaavalon/docker-cloudflare/blob/4a8888824dec0a1acccfb972e56fb57269fe100d/Dockerfile#L16

```
RUN apk add --update bash jq curl tzdata && \ 
```

Then, it should work.
