### ISSUE TITLE
[Question] what am I supposed to put in place of <TAG> ?

### ISSUE THREAD

**Issue by GStarSade** [joshuaavalon/docker-cloudflare#95]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Unknown

### Describe The Bug

Wasn't clear what I should replace TAG with. 

When I removed it it pulled several versions and unsure how to remove incorrect ones, log below.
When running it's also not clear where I should place the config file so I created an app folder in home and a config.yaml file.
Not sure if I need to include the short configuration file or all of it in config guide.

`Unable to find image 'ghcr.io/joshuaavalon/cloudflare-ddns:latest' locally
latest: Pulling from joshuaavalon/cloudflare-ddns
633ba29fd335: Pull complete
78920302c53a: Pull complete
ef11cae5c5cd: Pull complete
63d9af39f917: Pull complete
de8e99511ec6: Pull complete
ac779391a86c: Pull complete
c73c2020914b: Pull complete
6f41166a18a8: Pull complete
fa54c1d5b14e: Pull complete
0d12dc9fdfe3: Pull complete
40df94970c6d: Pull complete
Digest: sha256:916de725bc32b59a65a92803f3dad9ab5a2dae0777ba8922cb99237f2d2d14e1
Status: Downloaded newer image for ghcr.io/joshuaavalon/cloudflare-ddns:latest
03a636deb8b70c313f274cf7e1eb3a1b07c4b1dd112a8a8bbda8ecb172148985`

### Steps To Reproduce

` sudo docker run -d -v ./config.yaml:/app/config.yaml ghcr.io/joshuaavalon/cloudflare-ddns`

### Expected Behavior

cloudflare-ddns to install the correct version based on hardware.

**Comment by joshuaavalon** [comment]
`latest` does exists. See [here](https://github.com/joshuaavalon/docker-cloudflare/pkgs/container/cloudflare-ddns/113099129?tag=latest).

I don't know why you cannot pull.
